apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mysql.fullname" . }}-allow-backend
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "mysql.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: app-backend
      ports:
        - protocol: TCP
          port: 3306
