apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "frontend.fullname" . }}-egress-backend
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    # Allow DNS resolution (usually needed)
    - to:
        - namespaceSelector: {} 
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
    # Allow traffic to backend
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: app-backend
      ports:
        - protocol: TCP
          port: 80 # Service port
