apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "app-backend.fullname" . }}-allow-frontend
  labels:
    {{- include "app-backend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "app-backend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: frontend
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
