apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app-backend.fullname" . }}
  labels:
    {{- include "app-backend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app-backend.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
